const companies = [
  { id: 1, name: "TechNova Solutions", industry: "Software Development", founded: 2012, location: "Bangalore", employees: 500, description: "Provides web and mobile software solutions for global clients." },
  { id: 2, name: "FinEdge Analytics", industry: "Finance & Analytics", founded: 2015, location: "Mumbai", employees: 300, description: "Specializes in data-driven financial analytics and AI trading models." },
  { id: 3, name: "HealthBridge AI", industry: "Healthcare Technology", founded: 2018, location: "Pune", employees: 220, description: "Uses AI to enhance diagnostics and patient management systems." },
  { id: 4, name: "Cloudify Systems", industry: "Cloud Computing", founded: 2016, location: "Hyderabad", employees: 400, description: "Offers enterprise cloud hosting and DevOps services." },
  { id: 5, name: "EduSpark Learning", industry: "EdTech", founded: 2014, location: "Delhi", employees: 250, description: "Creates interactive online learning solutions and courses." },
  { id: 6, name: "CyberSafe Technologies", industry: "Cybersecurity", founded: 2013, location: "Noida", employees: 180, description: "Provides network and data protection for enterprises." },
  { id: 7, name: "GreenAgro Labs", industry: "AgriTech", founded: 2019, location: "Nagpur", employees: 120, description: "Develops IoT-based agricultural monitoring and automation systems." },
  { id: 8, name: "TravelSphere", industry: "Travel Technology", founded: 2011, location: "Chennai", employees: 350, description: "Delivers travel booking and itinerary management platforms." },
  { id: 9, name: "ByteForge Studios", industry: "Gaming", founded: 2017, location: "Kolkata", employees: 150, description: "Focuses on cross-platform video game development." },
  { id: 10, name: "BlueOcean Retail", industry: "E-Commerce", founded: 2010, location: "Jaipur", employees: 800, description: "Manages online marketplaces and retail logistics solutions." },
  { id: 11, name: "MediCore Diagnostics", industry: "Healthcare", founded: 2016, location: "Bhopal", employees: 230, description: "Creates diagnostic and health monitoring software." },
  { id: 12, name: "Zenith Robotics", industry: "Automation & Robotics", founded: 2020, location: "Pune", employees: 90, description: "Designs industrial robots and automation systems." },
  { id: 13, name: "InnovaSpace Tech", industry: "Aerospace", founded: 2014, location: "Hyderabad", employees: 400, description: "Innovates in aerospace software and satellite systems." },
  { id: 14, name: "BuildSmart Constructions", industry: "Construction Technology", founded: 2015, location: "Delhi", employees: 600, description: "Implements smart construction and monitoring platforms." },
  { id: 15, name: "SecureNet Pvt Ltd", industry: "IT Security", founded: 2012, location: "Noida", employees: 310, description: "Develops advanced firewall and intrusion detection systems." },
  { id: 16, name: "AgileTech Softwares", industry: "Software Consulting", founded: 2011, location: "Pune", employees: 450, description: "Provides scalable web and enterprise software services." },
  { id: 17, name: "OptiVision Labs", industry: "AI Research", founded: 2019, location: "Bangalore", employees: 200, description: "Focuses on computer vision and neural network technologies." },
  { id: 18, name: "NextGen Motors", industry: "Automotive", founded: 2010, location: "Chennai", employees: 700, description: "Produces electric vehicle systems and automation tech." },
  { id: 19, name: "DataWings", industry: "Big Data & Analytics", founded: 2017, location: "Mumbai", employees: 330, description: "Offers big data warehousing and predictive analytics." },
  { id: 20, name: "UrbanNest Realty", industry: "Real Estate", founded: 2013, location: "Hyderabad", employees: 260, description: "Provides smart real estate management software." },
  { id: 21, name: "CodeCrafters", industry: "Web Development", founded: 2015, location: "Pune", employees: 150, description: "Delivers responsive web solutions using modern stacks." },
  { id: 22, name: "MetaSoft AI", industry: "Artificial Intelligence", founded: 2020, location: "Bangalore", employees: 120, description: "Develops ML-driven software and predictive models." },
  { id: 23, name: "SmartBank Systems", industry: "FinTech", founded: 2018, location: "Mumbai", employees: 210, description: "Creates digital banking and online transaction solutions." },
  { id: 24, name: "FoodieBay Tech", industry: "FoodTech", founded: 2016, location: "Delhi", employees: 350, description: "Provides delivery tracking and restaurant management systems." },
  { id: 25, name: "EcoCharge Energy", industry: "CleanTech", founded: 2019, location: "Pune", employees: 190, description: "Works on renewable energy software and IoT solutions." },
  { id: 26, name: "TalentBridge HR", industry: "Recruitment Tech", founded: 2014, location: "Bangalore", employees: 300, description: "Builds platforms for recruitment and employee analytics." },
  { id: 27, name: "QuantumBit Labs", industry: "Research & Innovation", founded: 2021, location: "Hyderabad", employees: 80, description: "Explores quantum computing and emerging technologies." },
  { id: 28, name: "UrbanRider Mobility", industry: "Transport Tech", founded: 2015, location: "Chennai", employees: 270, description: "Provides ride-sharing and vehicle management apps." },
  { id: 29, name: "LegalEase", industry: "LegalTech", founded: 2017, location: "Noida", employees: 140, description: "Builds automation tools for law firms and legal research." },
  { id: 30, name: "VisionX Studios", industry: "Design & Animation", founded: 2016, location: "Kolkata", employees: 180, description: "Specializes in visual effects and 3D animation." },
  { id: 31, name: "ShopLink Technologies", industry: "E-Commerce", founded: 2013, location: "Mumbai", employees: 420, description: "Develops scalable online retail software." },
  { id: 32, name: "RoboMind Labs", industry: "AI & Robotics", founded: 2018, location: "Pune", employees: 130, description: "Focuses on AI-integrated automation systems." },
  { id: 33, name: "BuildOps", industry: "Construction Tech", founded: 2015, location: "Delhi", employees: 270, description: "Manages project tracking and site analytics tools." },
  { id: 34, name: "NextStep Consulting", industry: "Business Consulting", founded: 2010, location: "Gurgaon", employees: 380, description: "Provides IT and business strategy consulting." },
  { id: 35, name: "FarmLink Agri", industry: "AgriTech", founded: 2019, location: "Indore", employees: 110, description: "Develops precision farming and crop analytics software." },
  { id: 36, name: "BrightNet Telecom", industry: "Telecom", founded: 2012, location: "Chennai", employees: 600, description: "Offers mobile networking and telecom infrastructure solutions." },
  { id: 37, name: "SmartCity Infra", industry: "Infrastructure", founded: 2015, location: "Ahmedabad", employees: 420, description: "Provides IoT-enabled urban infrastructure management." },
  { id: 38, name: "TechVerse Studios", industry: "Software Development", founded: 2018, location: "Pune", employees: 200, description: "Creates web and enterprise-grade software." },
  { id: 39, name: "InspireHub Digital", industry: "Digital Marketing", founded: 2017, location: "Mumbai", employees: 260, description: "Delivers SEO, ads, and digital branding solutions." },
  { id: 40, name: "OmniTrade Logistics", industry: "Logistics & Supply Chain", founded: 2014, location: "Delhi", employees: 500, description: "Provides logistics software and delivery tracking systems." },
  { id: 41, name: "AeroNext Systems", industry: "Aerospace", founded: 2012, location: "Hyderabad", employees: 350, description: "Develops avionics software and flight analytics systems." },
  { id: 42, name: "BioCore Research", industry: "Biotech", founded: 2019, location: "Bangalore", employees: 170, description: "Focuses on life science innovations and genetic research." },
  { id: 43, name: "WaveLink Networks", industry: "Networking", founded: 2013, location: "Chennai", employees: 450, description: "Provides network optimization and 5G infrastructure services." },
  { id: 44, name: "PixelEdge Media", industry: "Creative & Media", founded: 2016, location: "Delhi", employees: 240, description: "Specializes in content creation and video production." },
  { id: 45, name: "DeepData Systems", industry: "Data Science", founded: 2018, location: "Pune", employees: 160, description: "Offers AI and analytics platforms for enterprises." },
  { id: 46, name: "CivicLabs", industry: "GovTech", founded: 2019, location: "Hyderabad", employees: 190, description: "Builds digital governance and citizen service platforms." },
  { id: 47, name: "Streamify", industry: "Entertainment", founded: 2017, location: "Mumbai", employees: 320, description: "Provides OTT streaming and media delivery systems." },
  { id: 48, name: "TechAssist IT", industry: "IT Services", founded: 2011, location: "Pune", employees: 380, description: "Offers cloud hosting, IT maintenance, and support." },
  { id: 49, name: "Visionary Labs", industry: "R&D", founded: 2020, location: "Bangalore", employees: 130, description: "Researches next-gen AI and sensor technologies." },
  { id: 50, name: "QuantumEdge", industry: "AI Research", founded: 2021, location: "Hyderabad", employees: 100, description: "Explores artificial intelligence and edge computing." }
];

export { companies };
