const companies = [
  { name: "TechNova Solutions", industry: "Software Development", founded: 2012, location: "Bangalore", employees: 500, description: "Provides web and mobile software solutions for global clients.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617557/logo.png" },
  { name: "FinEdge Analytics", industry: "Finance & Analytics", founded: 2015, location: "Mumbai", employees: 300, description: "Specializes in data-driven financial analytics and AI trading models.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-2.png" },
  { name: "HealthBridge AI", industry: "Healthcare Technology", founded: 2018, location: "Pune", employees: 220, description: "Uses AI to enhance diagnostics and patient management systems.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-3.png" },
  { name: "Cloudify Systems", industry: "Cloud Computing", founded: 2016, location: "Hyderabad", employees: 400, description: "Offers enterprise cloud hosting and DevOps services.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-4.png" },
  { name: "EduSpark Learning", industry: "EdTech", founded: 2014, location: "Delhi", employees: 250, description: "Creates interactive online learning solutions and courses.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-5.png" },
  { name: "CyberSafe Technologies", industry: "Cybersecurity", founded: 2013, location: "Noida", employees: 180, description: "Provides network and data protection for enterprises.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-6.png" },
  { name: "GreenAgro Labs", industry: "AgriTech", founded: 2019, location: "Nagpur", employees: 120, description: "Develops IoT-based agricultural monitoring and automation systems.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-7.png" },
  { name: "TravelSphere", industry: "Travel Technology", founded: 2011, location: "Chennai", employees: 350, description: "Delivers travel booking and itinerary management platforms.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-8.png" },
  { name: "ByteForge Studios", industry: "Gaming", founded: 2017, location: "Kolkata", employees: 150, description: "Focuses on cross-platform video game development.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-9.png" },
  { name: "BlueOcean Retail", industry: "E-Commerce", founded: 2010, location: "Jaipur", employees: 800, description: "Manages online marketplaces and retail logistics solutions.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-10.png" },

  { name: "MediCore Diagnostics", industry: "Healthcare", founded: 2016, location: "Bhopal", employees: 230, description: "Creates diagnostic and health monitoring software.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-11.png" },
  { name: "Zenith Robotics", industry: "Automation & Robotics", founded: 2020, location: "Pune", employees: 90, description: "Designs industrial robots and automation systems.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-12.png" },
  { name: "InnovaSpace Tech", industry: "Aerospace", founded: 2014, location: "Hyderabad", employees: 400, description: "Innovates in aerospace software and satellite systems.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-13.png" },
  { name: "BuildSmart Constructions", industry: "Construction Technology", founded: 2015, location: "Delhi", employees: 600, description: "Implements smart construction and monitoring platforms.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-14.png" },
  { name: "SecureNet Pvt Ltd", industry: "IT Security", founded: 2012, location: "Noida", employees: 310, description: "Develops advanced firewall and intrusion detection systems.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-15.png" },

  { name: "AgileTech Softwares", industry: "Software Consulting", founded: 2011, location: "Pune", employees: 450, description: "Provides scalable web and enterprise software services.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-16.png" },
  { name: "OptiVision Labs", industry: "AI Research", founded: 2019, location: "Bangalore", employees: 200, description: "Focuses on computer vision and neural network technologies.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-17.png" },
  { name: "NextGen Motors", industry: "Automotive", founded: 2010, location: "Chennai", employees: 700, description: "Produces electric vehicle systems and automation tech.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-18.png" },
  { name: "DataWings", industry: "Big Data & Analytics", founded: 2017, location: "Mumbai", employees: 330, description: "Offers big data warehousing and predictive analytics.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-19.png" },
  { name: "UrbanNest Realty", industry: "Real Estate", founded: 2013, location: "Hyderabad", employees: 260, description: "Provides smart real estate management software.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-20.png" },

  { name: "CodeCrafters", industry: "Web Development", founded: 2015, location: "Pune", employees: 150, description: "Delivers responsive web solutions using modern stacks.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-21.png" },
  { name: "MetaSoft AI", industry: "Artificial Intelligence", founded: 2020, location: "Bangalore", employees: 120, description: "Develops ML-driven software and predictive models.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-22.png" },
  { name: "SmartBank Systems", industry: "FinTech", founded: 2018, location: "Mumbai", employees: 210, description: "Creates digital banking and online transaction solutions.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-23.png" },
  { name: "FoodieBay Tech", industry: "FoodTech", founded: 2016, location: "Delhi", employees: 350, description: "Provides delivery tracking and restaurant management systems.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-24.png" },
  { name: "EcoCharge Energy", industry: "CleanTech", founded: 2019, location: "Pune", employees: 190, description: "Works on renewable energy software and IoT solutions.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-25.png" },

  { name: "TalentBridge HR", industry: "Recruitment Tech", founded: 2014, location: "Bangalore", employees: 300, description: "Builds platforms for recruitment and employee analytics.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-26.png" },
  { name: "QuantumBit Labs", industry: "Research & Innovation", founded: 2021, location: "Hyderabad", employees: 80, description: "Explores quantum computing and emerging technologies.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-27.png" },
  { name: "UrbanRider Mobility", industry: "Transport Tech", founded: 2015, location: "Chennai", employees: 270, description: "Provides ride-sharing and vehicle management apps.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-28.png" },
  { name: "LegalEase", industry: "LegalTech", founded: 2017, location: "Noida", employees: 140, description: "Builds automation tools for law firms and legal research.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-29.png" },
  { name: "VisionX Studios", industry: "Design & Animation", founded: 2016, location: "Kolkata", employees: 180, description: "Specializes in visual effects and 3D animation.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-30.png" },

  { name: "ShopLink Technologies", industry: "E-Commerce", founded: 2013, location: "Mumbai", employees: 420, description: "Develops scalable online retail software.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-31.png" },
  { name: "RoboMind Labs", industry: "AI & Robotics", founded: 2018, location: "Pune", employees: 130, description: "Focuses on AI-integrated automation systems.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-32.png" },
  { name: "BuildOps", industry: "Construction Tech", founded: 2015, location: "Delhi", employees: 270, description: "Manages project tracking and site analytics tools.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-33.png" },
  { name: "NextStep Consulting", industry: "Business Consulting", founded: 2010, location: "Gurgaon", employees: 380, description: "Provides IT and business strategy consulting.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-34.png" },
  { name: "FarmLink Agri", industry: "AgriTech", founded: 2019, location: "Indore", employees: 110, description: "Develops precision farming and crop analytics software.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-35.png" },

  { name: "BrightNet Telecom", industry: "Telecom", founded: 2012, location: "Chennai", employees: 600, description: "Offers mobile networking and telecom infrastructure solutions.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-36.png" },
  { name: "SmartCity Infra", industry: "Infrastructure", founded: 2015, location: "Ahmedabad", employees: 420, description: "Provides IoT-enabled urban infrastructure management.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-37.png" },
  { name: "TechVerse Studios", industry: "Software Development", founded: 2018, location: "Pune", employees: 200, description: "Creates web and enterprise-grade software.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-38.png" },
  { name: "InspireHub Digital", industry: "Digital Marketing", founded: 2017, location: "Mumbai", employees: 260, description: "Delivers SEO, ads, and digital branding solutions.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-39.png" },
  { name: "OmniTrade Logistics", industry: "Logistics & Supply Chain", founded: 2014, location: "Delhi", employees: 500, description: "Provides logistics software and delivery tracking systems.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-40.png" },

  { name: "AeroNext Systems", industry: "Aerospace", founded: 2012, location: "Hyderabad", employees: 350, description: "Develops avionics software and flight analytics systems.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-41.png" },
  { name: "BioCore Research", industry: "Biotech", founded: 2019, location: "Bangalore", employees: 170, description: "Focuses on life science innovations and genetic research.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-42.png" },
  { name: "WaveLink Networks", industry: "Networking", founded: 2013, location: "Chennai", employees: 450, description: "Provides network optimization and 5G infrastructure services.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-43.png" },
  { name: "PixelEdge Media", industry: "Creative & Media", founded: 2016, location: "Delhi", employees: 240, description: "Specializes in content creation and video production.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-44.png" },
  { name: "DeepData Systems", industry: "Data Science", founded: 2018, location: "Pune", employees: 160, description: "Offers AI and analytics platforms for enterprises.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-45.png" },

  { name: "CivicLabs", industry: "GovTech", founded: 2019, location: "Hyderabad", employees: 190, description: "Builds digital governance and citizen service platforms.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-46.png" },
  { name: "Streamify", industry: "Entertainment", founded: 2017, location: "Mumbai", employees: 320, description: "Provides OTT streaming and media delivery systems.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-47.png" },
  { name: "TechAssist IT", industry: "IT Services", founded: 2011, location: "Pune", employees: 380, description: "Offers cloud hosting, IT maintenance, and support.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-48.png" },
  { name: "Visionary Labs", industry: "R&D", founded: 2020, location: "Bangalore", employees: 130, description: "Researches next-gen AI and sensor technologies.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-49.png" },
  { name: "QuantumEdge", industry: "AI Research", founded: 2021, location: "Hyderabad", employees: 100, description: "Explores artificial intelligence and edge computing.", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765616897/50_reh7pu.png" }
];

export { companies };