const jobCompanyInfo = [
    {
      id: 1,
      companyName: "TechNova Solutions",
      jobTitle: "Frontend Developer",
      companySize: "500+ employees",
      companyType: "Product-based",
      website: "https://technova.com",
      workMode: "Hybrid",
      experience: "2–4 years",
      techStack: ["React", "JavaScript", "HTML", "CSS", "Redux"],
      perks: [
        "Flexible working hours",
        "Health insurance",
        "Learning budget",
        "Remote days"
      ],
      jobHighlights: [
        "Build scalable UI systems",
        "Work with senior frontend engineers",
        "Modern React architecture"
      ]
    },
  
    {
      id: 2,
      companyName: "FinEdge Analytics",
      jobTitle: "Data Analyst",
      companySize: "300+ employees",
      companyType: "Analytics & Finance",
      website: "https://finedge.ai",
      workMode: "Onsite",
      experience: "1–3 years",
      techStack: ["Python", "SQL", "Power BI", "Excel"],
      perks: [
        "Performance bonus",
        "Health cover",
        "Stock incentives"
      ],
      jobHighlights: [
        "Analyze real financial datasets",
        "Work with AI-driven insights",
        "Direct impact on trading models"
      ]
    },
  
    {
      id: 3,
      companyName: "HealthBridge AI",
      jobTitle: "AI Researcher",
      companySize: "200+ employees",
      companyType: "Healthcare AI",
      website: "https://healthbridge.ai",
      workMode: "Remote",
      experience: "3–6 years",
      techStack: ["Python", "TensorFlow", "PyTorch", "ML Ops"],
      perks: [
        "Fully remote",
        "Conference sponsorship",
        "Research grants"
      ],
      jobHighlights: [
        "Work on healthcare AI models",
        "Research-oriented environment",
        "Publish papers & patents"
      ]
    },
  
    {
      id: 4,
      companyName: "Cloudify Systems",
      jobTitle: "Cloud Engineer",
      companySize: "400+ employees",
      companyType: "Cloud Services",
      website: "https://cloudify.io",
      workMode: "Hybrid",
      experience: "2–5 years",
      techStack: ["AWS", "Azure", "Docker", "Kubernetes"],
      perks: [
        "Cloud certifications paid",
        "WFH support",
        "Annual tech bonus"
      ],
      jobHighlights: [
        "Design scalable cloud infra",
        "Work with Fortune 500 clients",
        "DevOps-driven culture"
      ]
    },
  
    {
      id: 5,
      companyName: "EduSpark Learning",
      jobTitle: "EdTech Developer",
      companySize: "250+ employees",
      companyType: "EdTech",
      website: "https://eduspark.com",
      workMode: "Remote",
      experience: "1–3 years",
      techStack: ["React", "Node.js", "MongoDB"],
      perks: [
        "Remote-first",
        "Paid learning programs",
        "Mental wellness support"
      ],
      jobHighlights: [
        "Build learning platforms",
        "Impact millions of students",
        "Fast-growing startup"
      ]
    },

    {
        id: 6,
        companyName: "CyberSafe Technologies",
        jobTitle: "Cybersecurity Analyst",
        companySize: "180+ employees",
        companyType: "Cybersecurity",
        website: "https://cybersafe.tech",
        workMode: "Hybrid",
        experience: "2–4 years",
        techStack: ["Network Security", "SIEM", "Firewalls"],
        perks: ["Security certifications", "Health insurance"],
        jobHighlights: ["Protect enterprise networks", "Threat monitoring"]
      },
      {
        id: 7,
        companyName: "GreenAgro Labs",
        jobTitle: "IoT Engineer",
        companySize: "120+ employees",
        companyType: "AgriTech",
        website: "https://greenagro.io",
        workMode: "Onsite",
        experience: "1–3 years",
        techStack: ["IoT", "Embedded C", "Sensors"],
        perks: ["Field allowances", "Innovation grants"],
        jobHighlights: ["Smart agriculture systems"]
      },
      {
        id: 8,
        companyName: "TravelSphere",
        jobTitle: "Travel App Developer",
        companySize: "350+ employees",
        companyType: "Travel Tech",
        website: "https://travelsphere.com",
        workMode: "Remote",
        experience: "2–4 years",
        techStack: ["React Native", "APIs"],
        perks: ["Travel credits", "Remote work"],
        jobHighlights: ["Build global travel apps"]
      },
      {
        id: 9,
        companyName: "ByteForge Studios",
        jobTitle: "Game Developer",
        companySize: "150+ employees",
        companyType: "Gaming",
        website: "https://byteforge.games",
        workMode: "Onsite",
        experience: "2–5 years",
        techStack: ["Unity", "C#", "3D Engines"],
        perks: ["Gaming gear", "Creative freedom"],
        jobHighlights: ["Cross-platform game dev"]
      },
      {
        id: 10,
        companyName: "BlueOcean Retail",
        jobTitle: "E-Commerce Manager",
        companySize: "800+ employees",
        companyType: "E-Commerce",
        website: "https://blueoceanretail.com",
        workMode: "Hybrid",
        experience: "4–7 years",
        techStack: ["Shopify", "Analytics", "CRM"],
        perks: ["Performance bonus", "Leadership role"],
        jobHighlights: ["Scale online marketplaces"]
      },
    
      {
        id: 11,
        companyName: "MediCore Diagnostics",
        jobTitle: "Lab Technician",
        companySize: "230+ employees",
        companyType: "Healthcare",
        website: "https://medicorelabs.com",
        workMode: "Onsite",
        experience: "1–3 years",
        techStack: ["Lab Systems", "Diagnostics"],
        perks: ["Medical insurance"],
        jobHighlights: ["Clinical testing operations"]
      },
      {
        id: 12,
        companyName: "Zenith Robotics",
        jobTitle: "Robotics Engineer",
        companySize: "90+ employees",
        companyType: "Robotics",
        website: "https://zenithrobotics.ai",
        workMode: "Onsite",
        experience: "2–5 years",
        techStack: ["ROS", "Automation", "Python"],
        perks: ["Hardware access", "R&D labs"],
        jobHighlights: ["Industrial robotics"]
      },
      {
        id: 13,
        companyName: "InnovaSpace Tech",
        jobTitle: "Aerospace Engineer",
        companySize: "400+ employees",
        companyType: "Aerospace",
        website: "https://innovaspace.tech",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["MATLAB", "Simulation"],
        perks: ["Research funding"],
        jobHighlights: ["Satellite systems"]
      },
      {
        id: 14,
        companyName: "BuildSmart Constructions",
        jobTitle: "Construction Project Manager",
        companySize: "600+ employees",
        companyType: "Construction Tech",
        website: "https://buildsmart.in",
        workMode: "Onsite",
        experience: "5–10 years",
        techStack: ["Project Tools", "IoT"],
        perks: ["Site allowances"],
        jobHighlights: ["Smart infrastructure"]
      },
      {
        id: 15,
        companyName: "SecureNet Pvt Ltd",
        jobTitle: "Network Security Specialist",
        companySize: "310+ employees",
        companyType: "IT Security",
        website: "https://securenet.com",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["Firewalls", "IDS", "VPN"],
        perks: ["Cert sponsorship"],
        jobHighlights: ["Enterprise security"]
      },
    
      {
        id: 16,
        companyName: "AgileTech Softwares",
        jobTitle: "Software Consultant",
        companySize: "450+ employees",
        companyType: "Consulting",
        website: "https://agiletech.io",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["Web Apps", "Client Systems"],
        perks: ["Client exposure"],
        jobHighlights: ["Enterprise consulting"]
      },
      {
        id: 17,
        companyName: "OptiVision Labs",
        jobTitle: "Computer Vision Engineer",
        companySize: "200+ employees",
        companyType: "AI Research",
        website: "https://optivision.ai",
        workMode: "Remote",
        experience: "2–5 years",
        techStack: ["OpenCV", "Deep Learning"],
        perks: ["Research bonuses"],
        jobHighlights: ["Vision AI models"]
      },
      {
        id: 18,
        companyName: "NextGen Motors",
        jobTitle: "Electric Vehicle Engineer",
        companySize: "700+ employees",
        companyType: "Automotive",
        website: "https://nextgenmotors.com",
        workMode: "Onsite",
        experience: "3–6 years",
        techStack: ["EV Systems", "Automation"],
        perks: ["EV benefits"],
        jobHighlights: ["Future mobility"]
      },
      {
        id: 19,
        companyName: "DataWings",
        jobTitle: "Big Data Engineer",
        companySize: "330+ employees",
        companyType: "Analytics",
        website: "https://datawings.io",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["Hadoop", "Spark"],
        perks: ["Cloud credits"],
        jobHighlights: ["Large data pipelines"]
      },
      {
        id: 20,
        companyName: "UrbanNest Realty",
        jobTitle: "Real Estate Analyst",
        companySize: "260+ employees",
        companyType: "Real Estate Tech",
        website: "https://urbannest.com",
        workMode: "Hybrid",
        experience: "2–4 years",
        techStack: ["Analytics", "Excel"],
        perks: ["Housing perks"],
        jobHighlights: ["Market insights"]
      },
      {
        id: 21,
        companyName: "CodeCrafters",
        jobTitle: "React Developer",
        companySize: "150+ employees",
        companyType: "Web Development",
        website: "https://codecrafters.dev",
        workMode: "Remote",
        experience: "2–4 years",
        techStack: ["React", "JavaScript", "CSS"],
        perks: ["Remote work", "Flexible hours"],
        jobHighlights: ["Modern frontend apps"]
      },
      {
        id: 22,
        companyName: "MetaSoft AI",
        jobTitle: "Machine Learning Engineer",
        companySize: "120+ employees",
        companyType: "AI",
        website: "https://metasoft.ai",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["Python", "TensorFlow", "ML"],
        perks: ["AI research budget"],
        jobHighlights: ["ML-driven products"]
      },
      {
        id: 23,
        companyName: "SmartBank Systems",
        jobTitle: "FinTech Developer",
        companySize: "210+ employees",
        companyType: "FinTech",
        website: "https://smartbank.tech",
        workMode: "Hybrid",
        experience: "2–5 years",
        techStack: ["Node.js", "APIs", "Security"],
        perks: ["Banking domain exposure"],
        jobHighlights: ["Digital banking systems"]
      },
      {
        id: 24,
        companyName: "FoodieBay Tech",
        jobTitle: "FoodTech Developer",
        companySize: "350+ employees",
        companyType: "FoodTech",
        website: "https://foodiebay.tech",
        workMode: "Remote",
        experience: "2–4 years",
        techStack: ["React", "Node.js"],
        perks: ["Free meals credits"],
        jobHighlights: ["Food delivery platforms"]
      },
      {
        id: 25,
        companyName: "EcoCharge Energy",
        jobTitle: "Renewable Energy Engineer",
        companySize: "190+ employees",
        companyType: "CleanTech",
        website: "https://ecocharge.energy",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["IoT", "Energy Systems"],
        perks: ["Green energy incentives"],
        jobHighlights: ["Clean energy solutions"]
      },
    
      {
        id: 26,
        companyName: "TalentBridge HR",
        jobTitle: "HR Tech Specialist",
        companySize: "300+ employees",
        companyType: "HR Tech",
        website: "https://talentbridge.io",
        workMode: "Remote",
        experience: "2–4 years",
        techStack: ["HR Analytics", "SaaS"],
        perks: ["Work-life balance"],
        jobHighlights: ["HR automation tools"]
      },
      {
        id: 27,
        companyName: "QuantumBit Labs",
        jobTitle: "Quantum Computing Researcher",
        companySize: "80+ employees",
        companyType: "Research",
        website: "https://quantumbit.ai",
        workMode: "Hybrid",
        experience: "4–8 years",
        techStack: ["Quantum Algorithms", "Python"],
        perks: ["Research grants"],
        jobHighlights: ["Quantum innovation"]
      },
      {
        id: 28,
        companyName: "UrbanRider Mobility",
        jobTitle: "Mobile App Developer",
        companySize: "270+ employees",
        companyType: "Mobility Tech",
        website: "https://urbanrider.app",
        workMode: "Hybrid",
        experience: "2–5 years",
        techStack: ["Flutter", "APIs"],
        perks: ["Travel allowance"],
        jobHighlights: ["Ride-sharing apps"]
      },
      {
        id: 29,
        companyName: "LegalEase",
        jobTitle: "LegalTech Developer",
        companySize: "140+ employees",
        companyType: "LegalTech",
        website: "https://legalease.io",
        workMode: "Remote",
        experience: "2–4 years",
        techStack: ["Node.js", "Automation"],
        perks: ["Flexible work"],
        jobHighlights: ["Legal automation"]
      },
      {
        id: 30,
        companyName: "VisionX Studios",
        jobTitle: "3D Animator",
        companySize: "180+ employees",
        companyType: "Design & Media",
        website: "https://visionx.studio",
        workMode: "Onsite",
        experience: "2–5 years",
        techStack: ["Blender", "3D Tools"],
        perks: ["Creative studio access"],
        jobHighlights: ["3D animation projects"]
      },
    
      {
        id: 31,
        companyName: "ShopLink Technologies",
        jobTitle: "E-Commerce Developer",
        companySize: "420+ employees",
        companyType: "E-Commerce",
        website: "https://shoplink.tech",
        workMode: "Hybrid",
        experience: "2–5 years",
        techStack: ["React", "Node.js"],
        perks: ["Performance bonus"],
        jobHighlights: ["Online retail systems"]
      },
      {
        id: 32,
        companyName: "RoboMind Labs",
        jobTitle: "AI Robotics Developer",
        companySize: "130+ employees",
        companyType: "AI Robotics",
        website: "https://robomind.ai",
        workMode: "Onsite",
        experience: "3–6 years",
        techStack: ["AI", "Robotics"],
        perks: ["R&D labs"],
        jobHighlights: ["AI robotics systems"]
      },
      {
        id: 33,
        companyName: "BuildOps",
        jobTitle: "Construction Tech Developer",
        companySize: "270+ employees",
        companyType: "Construction Tech",
        website: "https://buildops.tech",
        workMode: "Hybrid",
        experience: "2–5 years",
        techStack: ["SaaS", "Project Tools"],
        perks: ["Site exposure"],
        jobHighlights: ["Construction software"]
      },
      {
        id: 34,
        companyName: "NextStep Consulting",
        jobTitle: "Business Consultant",
        companySize: "380+ employees",
        companyType: "Consulting",
        website: "https://nextstep.consulting",
        workMode: "Hybrid",
        experience: "5–10 years",
        techStack: ["Strategy", "IT Consulting"],
        perks: ["Client travel"],
        jobHighlights: ["Business transformation"]
      },
      {
        id: 35,
        companyName: "FarmLink Agri",
        jobTitle: "AgriTech Developer",
        companySize: "110+ employees",
        companyType: "AgriTech",
        website: "https://farmlink.ag",
        workMode: "Onsite",
        experience: "1–3 years",
        techStack: ["IoT", "Data Analytics"],
        perks: ["Field incentives"],
        jobHighlights: ["Smart farming"]
      },
    
      {
        id: 36,
        companyName: "BrightNet Telecom",
        jobTitle: "Telecom Engineer",
        companySize: "600+ employees",
        companyType: "Telecom",
        website: "https://brightnet.tel",
        workMode: "Onsite",
        experience: "3–6 years",
        techStack: ["Networking", "5G"],
        perks: ["Telecom benefits"],
        jobHighlights: ["Network infrastructure"]
      },
      {
        id: 37,
        companyName: "SmartCity Infra",
        jobTitle: "Urban Infrastructure Engineer",
        companySize: "420+ employees",
        companyType: "Infrastructure",
        website: "https://smartcityinfra.com",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["IoT", "Urban Systems"],
        perks: ["Gov projects"],
        jobHighlights: ["Smart city projects"]
      },
      {
        id: 38,
        companyName: "TechVerse Studios",
        jobTitle: "Full Stack Developer",
        companySize: "200+ employees",
        companyType: "Software",
        website: "https://techverse.dev",
        workMode: "Hybrid",
        experience: "2–5 years",
        techStack: ["React", "Node.js"],
        perks: ["Tech learning budget"],
        jobHighlights: ["End-to-end apps"]
      },
      {
        id: 39,
        companyName: "InspireHub Digital",
        jobTitle: "Digital Marketing Specialist",
        companySize: "260+ employees",
        companyType: "Digital Marketing",
        website: "https://inspirehub.digital",
        workMode: "Remote",
        experience: "2–4 years",
        techStack: ["SEO", "Ads"],
        perks: ["Campaign bonuses"],
        jobHighlights: ["Brand growth"]
      },
      {
        id: 40,
        companyName: "OmniTrade Logistics",
        jobTitle: "Logistics Coordinator",
        companySize: "500+ employees",
        companyType: "Logistics",
        website: "https://omnitrade.io",
        workMode: "Onsite",
        experience: "2–5 years",
        techStack: ["Supply Chain Tools"],
        perks: ["Operational incentives"],
        jobHighlights: ["Supply chain ops"]
      },
    
      {
        id: 41,
        companyName: "AeroNext Systems",
        jobTitle: "Aerospace Software Engineer",
        companySize: "350+ employees",
        companyType: "Aerospace",
        website: "https://aeronext.systems",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["Avionics", "Simulation"],
        perks: ["Aerospace projects"],
        jobHighlights: ["Flight systems"]
      },
      {
        id: 42,
        companyName: "BioCore Research",
        jobTitle: "Biotech Researcher",
        companySize: "170+ employees",
        companyType: "Biotech",
        website: "https://biocorelabs.com",
        workMode: "Onsite",
        experience: "2–5 years",
        techStack: ["Bioinformatics"],
        perks: ["Research funding"],
        jobHighlights: ["Life science research"]
      },
      {
        id: 43,
        companyName: "WaveLink Networks",
        jobTitle: "Network Engineer",
        companySize: "450+ employees",
        companyType: "Networking",
        website: "https://wavelink.net",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["Routing", "Switching"],
        perks: ["Cert support"],
        jobHighlights: ["Enterprise networks"]
      },
      {
        id: 44,
        companyName: "PixelEdge Media",
        jobTitle: "Video Producer",
        companySize: "240+ employees",
        companyType: "Media",
        website: "https://pixeledge.media",
        workMode: "Onsite",
        experience: "2–5 years",
        techStack: ["Editing", "Production"],
        perks: ["Studio access"],
        jobHighlights: ["Digital content"]
      },
      {
        id: 45,
        companyName: "DeepData Systems",
        jobTitle: "Data Scientist",
        companySize: "160+ employees",
        companyType: "Data Science",
        website: "https://deepdata.ai",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["Python", "ML"],
        perks: ["AI projects"],
        jobHighlights: ["Advanced analytics"]
      },
    
      {
        id: 46,
        companyName: "CivicLabs",
        jobTitle: "GovTech Developer",
        companySize: "190+ employees",
        companyType: "GovTech",
        website: "https://civiclabs.gov",
        workMode: "Hybrid",
        experience: "2–5 years",
        techStack: ["Public Systems"],
        perks: ["Gov exposure"],
        jobHighlights: ["Citizen platforms"]
      },
      {
        id: 47,
        companyName: "Streamify",
        jobTitle: "Streaming App Developer",
        companySize: "320+ employees",
        companyType: "Entertainment Tech",
        website: "https://streamify.app",
        workMode: "Remote",
        experience: "2–5 years",
        techStack: ["Video Streaming", "APIs"],
        perks: ["OTT subscriptions"],
        jobHighlights: ["Media platforms"]
      },
      {
        id: 48,
        companyName: "TechAssist IT",
        jobTitle: "IT Support Engineer",
        companySize: "380+ employees",
        companyType: "IT Services",
        website: "https://techassist.io",
        workMode: "Onsite",
        experience: "1–3 years",
        techStack: ["IT Support", "Systems"],
        perks: ["Skill training"],
        jobHighlights: ["Enterprise IT support"]
      },
      {
        id: 49,
        companyName: "Visionary Labs",
        jobTitle: "AI Research Engineer",
        companySize: "130+ employees",
        companyType: "R&D",
        website: "https://visionarylabs.ai",
        workMode: "Hybrid",
        experience: "3–6 years",
        techStack: ["AI", "Sensors"],
        perks: ["Research grants"],
        jobHighlights: ["Next-gen AI"]
      },
      {
        id: 50,
        companyName: "QuantumEdge",
        jobTitle: "Edge Computing Specialist",
        companySize: "100+ employees",
        companyType: "AI Research",
        website: "https://quantumedge.ai",
        workMode: "Hybrid",
        experience: "4–7 years",
        techStack: ["Edge AI", "IoT", "C++"],
        perks: ["Research grants", "Flexible work"],
        jobHighlights: ["Edge intelligence"]
      }
    ];

    export { jobCompanyInfo };        