const jobs = [
  { title: "Frontend Developer", company: "TechNova Solutions", location: "Bangalore", type: "Full-time", salary: "₹6,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617557/logo.png", description: "Develop user interfaces using React, HTML, CSS, and JS." },
  { title: "Data Analyst", company: "FinEdge Analytics", location: "Mumbai", type: "Full-time", salary: "₹5,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-2.png", description: "Analyze financial datasets and prepare reports using Python and SQL." },
  { title: "AI Researcher", company: "HealthBridge AI", location: "Pune", type: "Full-time", salary: "₹8,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-3.png", description: "Research and develop AI models for healthcare solutions." },
  { title: "Cloud Engineer", company: "Cloudify Systems", location: "Hyderabad", type: "Full-time", salary: "₹7,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-4.png", description: "Manage and deploy cloud infrastructure using AWS/Azure." },
  { title: "EdTech Developer", company: "EduSpark Learning", location: "Delhi", type: "Full-time", salary: "₹5,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-5.png", description: "Develop interactive educational software platforms." },
  { title: "Cybersecurity Analyst", company: "CyberSafe Technologies", location: "Noida", type: "Full-time", salary: "₹6,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-6.png", description: "Monitor and secure enterprise networks." },
  { title: "IoT Engineer", company: "GreenAgro Labs", location: "Nagpur", type: "Full-time", salary: "₹6,20,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-7.png", description: "Design IoT solutions for smart agriculture." },
  { title: "Travel App Developer", company: "TravelSphere", location: "Chennai", type: "Full-time", salary: "₹5,90,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-8.png", description: "Build travel booking and itinerary apps." },
  { title: "Game Developer", company: "ByteForge Studios", location: "Kolkata", type: "Full-time", salary: "₹7,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-9.png", description: "Develop cross-platform video games using Unity." },
  { title: "E-Commerce Manager", company: "BlueOcean Retail", location: "Jaipur", type: "Full-time", salary: "₹6,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-10.png", description: "Manage online retail platforms and logistics." },

  { title: "Lab Technician", company: "MediCore Diagnostics", location: "Bhopal", type: "Full-time", salary: "₹4,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-11.png", description: "Handle diagnostic equipment and test reports." },
  { title: "Robotics Engineer", company: "Zenith Robotics", location: "Pune", type: "Full-time", salary: "₹7,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-12.png", description: "Design industrial automation and robotics systems." },
  { title: "Aerospace Engineer", company: "InnovaSpace Tech", location: "Hyderabad", type: "Full-time", salary: "₹8,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-13.png", description: "Develop satellite and aerospace software systems." },
  { title: "Construction Project Manager", company: "BuildSmart Constructions", location: "Delhi", type: "Full-time", salary: "₹9,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-14.png", description: "Oversee smart construction projects and monitoring." },
  { title: "Network Security Specialist", company: "SecureNet Pvt Ltd", location: "Noida", type: "Full-time", salary: "₹6,90,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-15.png", description: "Manage firewalls, intrusion detection, and network security." },

  { title: "Software Consultant", company: "AgileTech Softwares", location: "Pune", type: "Full-time", salary: "₹6,20,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-16.png", description: "Deliver web and enterprise software consulting services." },
  { title: "Computer Vision Engineer", company: "OptiVision Labs", location: "Bangalore", type: "Full-time", salary: "₹7,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-17.png", description: "Develop computer vision and AI models." },
  { title: "Electric Vehicle Engineer", company: "NextGen Motors", location: "Chennai", type: "Full-time", salary: "₹8,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-18.png", description: "Develop EV systems and automation technologies." },
  { title: "Big Data Engineer", company: "DataWings", location: "Mumbai", type: "Full-time", salary: "₹7,20,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-19.png", description: "Work with big data pipelines and analytics." },
  { title: "Real Estate Analyst", company: "UrbanNest Realty", location: "Hyderabad", type: "Full-time", salary: "₹5,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-20.png", description: "Analyze real estate trends and property data." },

  { title: "React Developer", company: "CodeCrafters", location: "Pune", type: "Full-time", salary: "₹6,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-21.png", description: "Develop responsive web applications using React." },
  { title: "Machine Learning Engineer", company: "MetaSoft AI", location: "Bangalore", type: "Full-time", salary: "₹8,20,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-22.png", description: "Develop ML models and AI solutions." },
  { title: "FinTech Developer", company: "SmartBank Systems", location: "Mumbai", type: "Full-time", salary: "₹7,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-23.png", description: "Develop digital banking platforms and APIs." },
  { title: "FoodTech Developer", company: "FoodieBay Tech", location: "Delhi", type: "Full-time", salary: "₹6,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-24.png", description: "Develop food delivery apps and management platforms." },
  { title: "Renewable Energy Engineer", company: "EcoCharge Energy", location: "Pune", type: "Full-time", salary: "₹6,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-25.png", description: "Develop clean energy and IoT solutions." },

  { title: "HR Tech Specialist", company: "TalentBridge HR", location: "Bangalore", type: "Full-time", salary: "₹5,90,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-26.png", description: "Develop recruitment and HR analytics software." },
  { title: "Quantum Computing Researcher", company: "QuantumBit Labs", location: "Hyderabad", type: "Full-time", salary: "₹9,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-27.png", description: "Work on quantum algorithms and simulations." },
  { title: "Mobile App Developer", company: "UrbanRider Mobility", location: "Chennai", type: "Full-time", salary: "₹6,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-28.png", description: "Develop ride-sharing mobile applications." },
  { title: "LegalTech Developer", company: "LegalEase", location: "Noida", type: "Full-time", salary: "₹5,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-29.png", description: "Build tools for legal research and law firms." },
  { title: "3D Animator", company: "VisionX Studios", location: "Kolkata", type: "Full-time", salary: "₹5,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-30.png", description: "Create 3D models and animations for media." },

  { title: "E-Commerce Developer", company: "ShopLink Technologies", location: "Mumbai", type: "Full-time", salary: "₹6,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-31.png", description: "Develop online shopping platforms." },
  { title: "AI Robotics Developer", company: "RoboMind Labs", location: "Pune", type: "Full-time", salary: "₹7,20,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-32.png", description: "Develop AI-driven robotics solutions." },
  { title: "Construction Tech Developer", company: "BuildOps", location: "Delhi", type: "Full-time", salary: "₹6,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-33.png", description: "Develop construction project management software." },
  { title: "Business Consultant", company: "NextStep Consulting", location: "Gurgaon", type: "Full-time", salary: "₹9,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-34.png", description: "Provide IT and business consulting services." },
  { title: "AgriTech Developer", company: "FarmLink Agri", location: "Indore", type: "Full-time", salary: "₹5,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-35.png", description: "Develop precision farming and crop analytics tools." },

  { title: "Telecom Engineer", company: "BrightNet Telecom", location: "Chennai", type: "Full-time", salary: "₹7,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-36.png", description: "Work on telecom networks and mobile infrastructure." },
  { title: "Urban Infrastructure Engineer", company: "SmartCity Infra", location: "Ahmedabad", type: "Full-time", salary: "₹7,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-37.png", description: "Develop IoT-based urban infrastructure solutions." },
  { title: "Full Stack Developer", company: "TechVerse Studios", location: "Pune", type: "Full-time", salary: "₹6,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-38.png", description: "Develop web applications using full stack technologies." },
  { title: "Digital Marketing Specialist", company: "InspireHub Digital", location: "Mumbai", type: "Full-time", salary: "₹5,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-39.png", description: "Plan and execute digital marketing campaigns." },
  { title: "Logistics Coordinator", company: "OmniTrade Logistics", location: "Delhi", type: "Full-time", salary: "₹6,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-40.png", description: "Coordinate supply chain and logistics operations." },

  { title: "Aerospace Software Engineer", company: "AeroNext Systems", location: "Hyderabad", type: "Full-time", salary: "₹8,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-41.png", description: "Develop avionics software and flight analytics." },
  { title: "Biotech Researcher", company: "BioCore Research", location: "Bangalore", type: "Full-time", salary: "₹7,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-42.png", description: "Conduct research in life sciences and genetics." },
  { title: "Network Engineer", company: "WaveLink Networks", location: "Chennai", type: "Full-time", salary: "₹7,20,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-43.png", description: "Design and optimize networking solutions." },
  { title: "Video Producer", company: "PixelEdge Media", location: "Delhi", type: "Full-time", salary: "₹5,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-44.png", description: "Produce and edit digital content." },
  { title: "Data Scientist", company: "DeepData Systems", location: "Pune", type: "Full-time", salary: "₹8,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-45.png", description: "Analyze datasets and build AI solutions." },

  { title: "GovTech Developer", company: "CivicLabs", location: "Hyderabad", type: "Full-time", salary: "₹6,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-46.png", description: "Develop citizen service platforms for governance." },
  { title: "Streaming App Developer", company: "Streamify", location: "Mumbai", type: "Full-time", salary: "₹6,50,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-47.png", description: "Build OTT and media streaming platforms." },
  { title: "IT Support Engineer", company: "TechAssist IT", location: "Pune", type: "Full-time", salary: "₹5,80,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-48.png", description: "Provide IT maintenance and support." },
  { title: "AI Research Engineer", company: "Visionary Labs", location: "Bangalore", type: "Full-time", salary: "₹8,20,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765617642/logo-49.png", description: "Research next-gen AI and sensor technology." },
  { title: "Edge Computing Specialist", company: "QuantumEdge", location: "Hyderabad", type: "Full-time", salary: "₹9,00,000/yr", logo: "https://res.cloudinary.com/dct17gxgo/image/upload/v1765616897/50_reh7pu.png", description: "Develop edge computing and AI platforms." }
];

export { jobs };